; Listing generated by Microsoft (R) Optimizing Compiler Version 19.42.34435.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	A
EXTRN	__security_check_cookie:PROC
A	DQ	ffffffffffffffffH
_DATA	ENDS
PUBLIC	main
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File D:\Assembly Project\Mul\Loop.c
; Line 5
	xor	eax, eax
	cmp	QWORD PTR A, 1
	jb	SHORT $LN2@main
	mov	QWORD PTR A, rax
$LN2@main:
; Line 8
	ret	0
main	ENDP
_TEXT	ENDS
END
